name: build-deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Key (Optional)
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: github.com  

      - name: Add my-origin remote (Optional)
        run: |
          git remote add my-origin git@github.com:Tender6795/edu_tech.git || echo "my-origin already exists"

      - name: Fetch latest changes from my-origin (Optional)
        run: |
          git fetch my-origin dev  # Update local copy of my-origin's dev branch (optional)

      - name: Force Push with --force-with-lease (Recommended)
        run: |
          git push my-origin HEAD:dev --force-with-lease